// vue/eleme/src/App.vue
<!--
 * @Description: 
 * @version: 
 * @Author: LuyunSheng
 * @Date: 2022-09-15 19:51:02
 * @LastEditTime: 2022-09-15 21:04:03
-->
<template>
    <div>
        <v-header :seller="seller" />
    </div>
</template>
<script>
import { getSellerRequest } from './api/request';
import header from './components/header/header.vue';
export default {
    data() {
        return {
            seller: {},
        };
    },
    mounted() {
        const getSellerData = async () => {
            const { data } = await getSellerRequest();
            this.seller = data;
            console.log(this.seller);
        };
        getSellerData();
    },
    components: {
        'v-header': header,
    },
};
</script>
<style scoped></style>

// interview/react/effect-unmount-promise/src/App.tsx
/*
 * @Description: 
 * @version: 
 * @Author: LuyunSheng
 * @Date: 2022-08-25 16:26:12
 * @LastEditTime: 2022-08-25 16:30:28
 */
import { useState } from 'react'
import MyComponent from './MyComponent'

function App() {

  return (
    <div className="App">
      <MyComponent/>
    </div>
  )
}

export default App
